name: 'Register build artifact'
description: 'Creates an artifact version association with the workflow run'

inputs:
  cloudbees-url:
    description: 'The CloudBees platform URL.'
    required: true
  cloudbees-pat:
    description: 'The CloudBees platform personal access token.'
    required: true
  component-id:
    description: 'The CloudBees platform component ID.'
    required: true
  name:
    description: 'The name of the artifact.'
    required: true
  version:
    description: 'The version of the artifact.'
    required: true
  url:
    description: 'The url where the artifact version is located e.g. docker.io/myapp/myimg:1.0.0.'
    required: true
  digest:
    description: 'The artifact digest that uniquely and immutably identifies the artifact.'

runs:
  using: composite
  steps:
    - id: registerBuildArtifact
      name: Register CloudBees Build Artifact
      shell: bash
      run: |
        #Create payload
        echo '{ "name": "'"$INPUT_NAME"'", "url": "'"$INPUT_URL"'", "version": "'"$INPUT_VERSION"'", ' > /tmp/payload.json
        echo '"operation": "'"PUBLISHED"'", "sourceUrl":"'"$GITHUB_RUN_URL"'", "digest": "'"$INPUT_DIGEST"'" }' >> /tmp/payload.json

        #DEBUG
        echo This is the payload
        cat /tmp/payload.json
        echo This is the POST
        echo "$INPUT_CLOUDBEES_URL/v2/resources/$INPUT_COMPONENT_ID/artifactinfos"
        echo CLOUDBEES_PLATFORM_PAT="$INPUT_JWT"
        echo CLOUDBEES_PLATFORM_URL="$INPUT_CLOUDBEES_URL"

        # Make Platform API call to create artifact_info record
        response=$(curl --fail-with-body  -X 'POST' "$INPUT_CLOUDBEES_URL/v2/resources/$INPUT_COMPONENT_ID/artifactinfos" \
          -H "Authorization: Bearer $INPUT_JWT" -H 'Content-Type: application/json' \
          --data-binary '@/tmp/payload.json') || command_failed=1
        
        # Check curl exit code
        if [ ${command_failed:-0} -eq 1 ];
        then
          echo "Platform API call failed with error: '$response'"
          exit 1
        fi
      env:
        INPUT_JWT: ${{ inputs.cloudbees-pat }}
        INPUT_CLOUDBEES_URL: ${{ inputs.cloudbees-url }}
        INPUT_COMPONENT_ID: ${{ inputs.component-id }}
        INPUT_NAME: ${{ inputs.name }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_URL: ${{ inputs.url }}
        INPUT_DIGEST: ${{ inputs.digest }}
        GITHUB_RUN_URL: ${{ github.repositoryUrl }}/actions/jobs/${{ github.job }}
