apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  Test1:
    steps:
      - name: Checkout1
        uses: cloudbees-io/checkout/.cloudbees/testing@CBP-10833
        id: checkout1
        env:
          RUNNER_DEBUG: "1"        
      - name: Commit1
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Commit 1:"
          if [${{ steps.checkout1.outputs.provider }} != 'github']; then
            echo Error: Provider=${{ steps.checkout1.outputs.provider }}, expected 'github'
            exit 1
          fi
          echo Repository URL = ${{ steps.checkout1.outputs.repository-url }}
          echo Commit ID = ${{ steps.checkout1.outputs.commit-id }}
          echo Commit URL = ${{ steps.checkout1.outputs.commit-url }}
          echo Ref = ${{ steps.checkout1.outputs.ref }}
  Test2:
    steps:
      - name: Checkout2
        uses: cloudbees-io/checkout/.cloudbees/testing@CBP-10833
        id: checkout2
        with:
            provider: "github"
            repository: "rthomascb/anotherrepo"
            ref: v1
        env:
          RUNNER_DEBUG: "1"        
      - name: Commit2
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Commit 2:"
          echo "Inputs:"
          echo "  provider: github"
          echo "  repository: rthomascb/anotherrepo"
          echo "  ref v1"
          echo Provider = ${{ steps.checkout2.outputs.provider }}
          echo Repository URL = ${{ steps.checkout2.outputs.repository-url }}
          echo Commit ID = ${{ steps.checkout2.outputs.commit-id }}
          echo Commit URL = ${{ steps.checkout2.outputs.commit-url }}
          echo Ref = ${{ steps.checkout2.outputs.ref }}
  Test3:
    steps:
      - name: Checkout3
        uses: cloudbees-io/checkout/.cloudbees/testing@CBP-10833
        id: checkout3
        with:
            provider: "github"
            repository: "rthomascb/anotherrepo"
            ref: 5991d1070a23ed3e5343218e6a0e8b79ce8a174c
        env:
          RUNNER_DEBUG: "1"        
      - name: Commit3
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Commit 3:"
          echo "Inputs:"
          echo "  provider: github"
          echo "  repository: rthomascb/anotherrepo"
          echo "  ref 5991d1070a23ed3e5343218e6a0e8b79ce8a174c"
          echo Provider = ${{ steps.checkout3.outputs.provider }}
          echo Repository URL = ${{ steps.checkout3.outputs.repository-url }}
          echo Commit ID = ${{ steps.checkout3.outputs.commit-id }}
          echo Commit URL = ${{ steps.checkout3.outputs.commit-url }}
          echo Ref = ${{ steps.checkout3.outputs.ref }}
  Test4:
    steps:
      - name: Checkout4
        uses: cloudbees-io/checkout/.cloudbees/testing@CBP-10833
        id: checkout4
        with:
            provider: "gitlab"
            repository: "rthomascb/actionman3"
            token: ${{ secrets.gitlab_PAT }}
        env:
          RUNNER_DEBUG: "1"        
      - name: Commit4
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Commit 4:"
          echo "Inputs:"
          echo "  provider: gitlab"
          echo "  repository: https://gitlab.com/rthomascb/actionman3"
          echo Provider = ${{ steps.checkout4.outputs.provider }}
          echo Repository URL = ${{ steps.checkout4.outputs.repository-url }}
          echo Commit ID = ${{ steps.checkout4.outputs.commit-id }}
          echo Commit URL = ${{ steps.checkout4.outputs.commit-url }}
          echo Ref = ${{ steps.checkout4.outputs.ref }}



