apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Checkout1
        uses: cloudbees-io/checkout/.cloudbees/testing@CBP-10833
        id: checkout1
        env:
          RUNNER_DEBUG: "1"        
      - name: Checkout2
        uses: cloudbees-io/checkout/.cloudbees/testing@CBP-10833
        id: checkout2
        with:
            provider: "github"
        env:
          RUNNER_DEBUG: "1"        
      - name: Commit
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Commit details:"
          echo Provider = ${{ steps.checkout1.outputs.provider }}
          echo Repository URL = ${{ steps.checkout1.outputs.repository-url }}
          echo Commit ID = ${{ steps.checkout1.outputs.commit-id }}
          echo Commit URL = ${{ steps.checkout1.outputs.commit-url }}
          echo Branch = ${{ steps.checkout1.outputs.branch }}

