apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  build_by_repo:
    steps:
      - name: Checkout1
        uses: cloudbees-io/checkout/.cloudbees/testing@CBP-10833
        id: checkout1
        env:
          RUNNER_DEBUG: "1"        
      - name: Commit1
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Commit 1:"
          echo Provider = ${{ steps.checkout1.outputs.provider }}
          echo Repository URL = ${{ steps.checkout1.outputs.repository-url }}
          echo Commit ID = ${{ steps.checkout1.outputs.commit-id }}
          echo Commit URL = ${{ steps.checkout1.outputs.commit-url }}
          echo Branch = ${{ steps.checkout1.outputs.branch }}
  build_by_tag:
    steps:
      - name: Checkout2
        uses: cloudbees-io/checkout/.cloudbees/testing@CBP-10833
        id: checkout2
        with:
            provider: "github"
            repository: "rthomascb/anotherrepo"
            ref: v1
        env:
          RUNNER_DEBUG: "1"        
      - name: Commit2
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Commit 2:"
          echo Provider = ${{ steps.checkout2.outputs.provider }}
          echo Repository URL = ${{ steps.checkout2.outputs.repository-url }}
          echo Commit ID = ${{ steps.checkout2.outputs.commit-id }}
          echo Commit URL = ${{ steps.checkout2.outputs.commit-url }}
          echo Branch = ${{ steps.checkout2.outputs.branch }}
  build_by_commit_id:
    steps:
      - name: Checkout3
        uses: cloudbees-io/checkout/.cloudbees/testing@CBP-10833
        id: checkout3
        with:
            provider: "github"
            repository: "rthomascb/anotherrepo"
            ref: 5991d1070a23ed3e5343218e6a0e8b79ce8a174c
        env:
          RUNNER_DEBUG: "1"        
      - name: Commit3
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Commit 2:"
          echo Provider = ${{ steps.checkout3.outputs.provider }}
          echo Repository URL = ${{ steps.checkout3.outputs.repository-url }}
          echo Commit ID = ${{ steps.checkout3.outputs.commit-id }}
          echo Commit URL = ${{ steps.checkout3.outputs.commit-url }}
          echo Branch = ${{ steps.checkout3.outputs.branch }}


