apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@df145d4f0268a205ebb6cc6f48a44109d8c357d9
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Display commit ID"


