apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout:latest
        id: checkout
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
          echo ID= ${{ steps.checkout.outputs.commit-id }}
          echo URL= ${{ steps.checkout.outputs.commit-url }}

