apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout/.cloudbees/testing@CBP-10833
        id: checkout
      - name: Commit
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Commit details:"
          echo Provider = ${{ steps.checkout.outputs.provider }}
          echo Repository URL = ${{ steps.checkout.outputs.repository-url }}
          echo Commit ID= ${{ steps.checkout.outputs.commit-id }}
          echo Commit URL= ${{ steps.checkout.outputs.commit-url }}

