apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: label artifact version
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: step1
        uses: http://github.com/cloudbees-io/label-artifact-version@v1

