apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: label artifact version
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: step1
        uses: http://github.com/cloudbees-io/label-artifact-version@CBP-12420
        with:
          component-id: 065b2595-cd1e-415d-9c5b-cab06074b641
          artifact-id: f089759c-9a6c-4c5b-befb-d70ca006625c
          labels: "Enter,     your labels,here!    , Thanks."
          operation: "ADD"
