apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: label artifact version
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: step1
        uses: http://github.com/cloudbees-io/label-artifact-version@CBP-12420
        with:
          component-id: 172f9991-e542-4605-958f-3ab17f2f5cda
          artifact-id: af204f43-58cc-43c4-92ad-b689f8aa3f07
          labels: "Enter,     your labels,here!    , Thanks."
          operation: "ADD"
