apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Deploy artifact
        uses: cloudbees-io/register-deployed-artifact@c9161888bb278f5c4d3818d9e6f886588a80bec2
        with:
          name: "rtFactRegisterDep"
          version: "1.0.0"
          url: "docker.io/myapp/myimg:1.0.0"
          digest: "sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b3609"
          target-environment: "test env"


