apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterBuildArtifact
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build1:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@1601419546d4af0e0ceef77d3e89b779a0874488
        continue-on-error: true
        with:
          name: "rtFactRegister"
          version: "1.0.0"
          url: "docker.io/myapp/myimg:1.0.0"
          digest: "sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b3609"
  build2:
    steps:
      - name: Fail with missing name
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: ""
          version: "1.0.0"
          url: "docker.io/myapp/myimg:1.0.0"
          digest: ""
  build3:
    steps:
      - name: Fail with missing version
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "MyName"
          version: ""
          url: "docker.io/myapp/myimg:1.0.0"
          digest: ""
  build4:
    steps:
      - name: Fail with missing URL
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "MyName"
          version: "MyVersion"
          url: ""
          digest: ""   

  