apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
    - id: createArtifactInfo3
      name: Create deployed artifact info w/o digest
      uses: docker://alpine/curl:latest
      run: |
        response=$(curl -i -X 'POST' "$URL/v2/workflows/runs/artifactinfos" -d "{\"runId\": \"$RUN_ID\", \"runAttempt\": \"$RUN_ATTEMPT\", \"name\": \"testArt\", \"url\": \"https://test.url/$RANDOM\", \"version\": \"$RANDOM\", \"type\": \"test\", \"operation\": \"DEPLOYED\"}" -H "Authorization: Bearer $JWT" -H 'Content-Type: application/json') || command_failed=1
        
        # Check response
        if [ ${command_failed:-0} -eq 1 ];
        then
          echo "Failed with response '$response'"
          exit 1
        fi

        echo "Success with response '$response'"
        exit 0
      env:
        JWT: ${{ cloudbees.api.token }}
        URL: ${{ cloudbees.api.url }}
        RUN_ID: ${{ cloudbees.run_id }}
        RUN_ATTEMPT: ${{ cloudbees.run_attempt }}

