apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterBuildArtifact
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        continue-on-error: true
        with:
          name: "rtFactRegister"
          version: "1.0.0"
          url: "docker.io/myapp/myimg:1.0.0"
          digest: "sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b3609"
      - name: Log Step 2 Complete
        uses: docker://golang:1.20.3-alpine3.17
        run: echo "Completed Step 2"
        continue-on-error: true
      - name: Log Step 3 Complete
        uses: docker://golang:1.20.3-alpine3.17
        run: echo "Completed Step 3"
        continue-on-error: true
      - name: Fail with missing name
        id: failstep1
        uses: cloudbees-io/register-build-artifact@v1
        continue-on-error: true
        with:
          name: ""
          version: "1.0.0"
          url: "docker.io/myapp/myimg:1.0.0"
          digest: ""
      - name: Fail with missing version
        if: always()
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "MyName"
          version: ""
          url: "docker.io/myapp/myimg:1.0.0"
          digest: ""
      - name: Print complete
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"