apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Scheduled Workflow
on:
  push:
    branches:
      - "**"
  schedule:
    - cron: 1 2 3 4 5 6 7 8 9 0 
jobs:
  build:
    steps:
      - name: Run me every 5 minutes
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world every 5 minutes"
