apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Scheduled Workflow
on:
  push:
    branches:
      - "**"
  schedule:
    - cron: 0,5,10,15,20,25,30,35,40,45,50,55 * * * *
jobs:
  build:
    steps:
      - name: Run me every 5 minutes
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
