apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Scheduled Workflow
on:
  push:
    branches:
      - "**"
  schedule:
    - cron: 20,25,30,35,40 * * * *
jobs:
  build:
    steps:
      - name: Run me every six seconds
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world again"
