#Creates an artifact version association with the workflow run.
name: 'Register build artifact TEST'

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: Deploy artifact
        uses: ./.github/actions/register-build-artifact
        with:
          component-id: "172f9991-e542-4605-958f-3ab17f2f5cda"
          name: "rtFactRegisterFromGitHub"
          version: "1.0.0"
          url: "docker.io/myapp/myimg:1.0.0"
          digest: "sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b3609"
          cloudbees-url: ${{ vars.CLOUDBEES_PLATFORM_URL }}
          cloudbees-pat: ${{ secrets.CLOUDBEES_PLATFORM_PAT }}
